### ISSUE TITLE
Error - Unsupported item key.

### ISSUE THREAD

**Issue by ykslol** [RichardKav/zabbix-nvidia-smi-integration#2]
I added template and userparams into zabbix-agent config.
In web interface an error that keys are unsupported, but from zabbix-server host:
zabbix_get -s host -k gpu.free   returns current count of free memory.

zabbix_agentd (daemon) (Zabbix) 3.2.6  Ubuntu 16.04    (all cheks works by hands and throu zabbix_get)

zabbix_server (Zabbix) 3.2.6 ( Centos 7.3)

**Comment by RichardKav** [comment]
Is there anything in the Zabbix agent logs? or any additional information regarding the error?

Looking around on forums regarding similar errors indicates some kind of synchronisation issue:
- https://zabbix.com/forum/showthread.php?p=186939
- https://github.com/lorf/zapache/issues/2
- https://zabbix.com/forum/showthread.php?p=186939

**Comment by ykslol** [comment]
My hostname and dns name are match. It is a hardware, not virtual host. In log the same discription of the error as in zabbix_web interface:

 21482:20170718:162403.067 item "miner.yksys.pro:gpu.fanspeed" became not supported: Unsupported item key.
It is with the all gpu checks

But
zabbix_get -s miner.yksys.pro -k gpu.free
7432
Works with DNS and with Ip

Nothing 'criminal' in zabbix_agent log

**Comment by RichardKav** [comment]
There are several things that you might be able to try:

1.  A first basic test would be to see if the nvidia-smi command itself works. i.e.

`nvidia-smi --query-gpu=fan.speed --format=csv,noheader,nounits -i 0`

For some cards that are passively cooled it will report "[Not Supported]".

2.  Restarting both the agents and the main server might also help as per: https://www.zabbix.com/forum/showthread.php?t=52083

3.  If you move your mouse over the red cross in the "Info" column, you should have the reason why your 
items are unsupported. 

4.  Looking around it might be that the polling rate is too high, and that the command is having difficulty responding in a timely fashion: https://sourceforge.net/p/zabbix/mailman/message/34913783/. Looking at code changes in https://github.com/ejimz/Elasticsearch-zabbix/issues/10, they seem to introduce caching to get over similar issues, though in your case slowing the polling rate down might help.

5. In another example if the data isn't been sent by the agent for a short while this might also happen: https://github.com/jitlogic/zorka/issues/174. I/O bottlenecking in https://github.com/zbx-sadman/unifi_miner/issues/4 seems to have caused these sort of issues as well. 

6.  In https://serverfault.com/questions/761645/zabbix-issue-with-lld-lots-of-became-supported-became-not-supported they seem to switch in the template between 'Agent (active)' to 'Zabbix Trapper' in order to aid with the timing issues.

**Comment by forging2012** [comment]
修改item类型为：Zabbix agent (active)即可。
Zabbix agent (active)

**Comment by forging2012** [comment]
change item type to Zabbix agent (active) is OK.
